namespace Fable.Browser

module Dom =

    open System
    open Fable.Core

    // let [<Global>] ANGLE_instanced_arrays: ANGLE_instanced_arraysType = jsNative
    // let [<Global>] AnalyserNode: AnalyserNodeType = jsNative
    // let [<Global>] AnimationEvent: AnimationEventType = jsNative
    // let [<Global>] ApplicationCache: ApplicationCacheType = jsNative
    // let [<Global>] AriaRequestEvent: AriaRequestEventType = jsNative
    let [<Global>] Attr: AttrType = jsNative
    // let [<Global>] AudioBuffer: AudioBufferType = jsNative
    // let [<Global>] AudioBufferSourceNode: AudioBufferSourceNodeType = jsNative
    // let [<Global>] AudioContext: AudioContextType = jsNative
    // let [<Global>] AudioDestinationNode: AudioDestinationNodeType = jsNative
    // let [<Global>] AudioListener: AudioListenerType = jsNative
    // let [<Global>] AudioNode: AudioNodeType = jsNative
    // let [<Global>] AudioParam: AudioParamType = jsNative
    // let [<Global>] AudioProcessingEvent: AudioProcessingEventType = jsNative
    // let [<Global>] AudioTrack: AudioTrackType = jsNative
    // let [<Global>] AudioTrackList: AudioTrackListType = jsNative
    // let [<Global>] AudioWorker: AudioWorkerType = jsNative
    // let [<Global>] AudioWorkerGlobalScope: AudioWorkerGlobalScopeType = jsNative
    // let [<Global>] AudioWorkerNode: AudioWorkerNodeType = jsNative
    // let [<Global>] AudioWorkerNodeProcessor: AudioWorkerNodeProcessorType = jsNative
    // let [<Global>] BarProp: BarPropType = jsNative
    // let [<Global>] BeforeUnloadEvent: BeforeUnloadEventType = jsNative
    // let [<Global>] BiquadFilterNode: BiquadFilterNodeType = jsNative
    // let [<Global>] Blob: BlobType = jsNative
    let [<Global>] CDATASection: CDATASectionType = jsNative
    // let [<Global>] CSS: CSS = jsNative
    // let [<Global>] CSSConditionRule: CSSConditionRuleType = jsNative
    // let [<Global>] CSSFontFaceRule: CSSFontFaceRuleType = jsNative
    // let [<Global>] CSSGroupingRule: CSSGroupingRuleType = jsNative
    // let [<Global>] CSSImportRule: CSSImportRuleType = jsNative
    // let [<Global>] CSSKeyframeRule: CSSKeyframeRuleType = jsNative
    // let [<Global>] CSSKeyframesRule: CSSKeyframesRuleType = jsNative
    // let [<Global>] CSSMediaRule: CSSMediaRuleType = jsNative
    // let [<Global>] CSSNamespaceRule: CSSNamespaceRuleType = jsNative
    // let [<Global>] CSSPageRule: CSSPageRuleType = jsNative
    // let [<Global>] CSSRule: CSSRuleType = jsNative
    // let [<Global>] CSSRuleList: CSSRuleListType = jsNative
    // let [<Global>] CSSStyleDeclaration: CSSStyleDeclarationType = jsNative
    // let [<Global>] CSSStyleRule: CSSStyleRuleType = jsNative
    // let [<Global>] CSSStyleSheet: CSSStyleSheetType = jsNative
    // let [<Global>] CSSSupportsRule: CSSSupportsRuleType = jsNative
    let [<Global>] CanvasGradient: CanvasGradientType = jsNative
    let [<Global>] CanvasPattern: CanvasPatternType = jsNative
    let [<Global>] CanvasRenderingContext2D: CanvasRenderingContext2DType = jsNative
    // let [<Global>] ChannelMergerNode: ChannelMergerNodeType = jsNative
    // let [<Global>] ChannelSplitterNode: ChannelSplitterNodeType = jsNative
    // let [<Global>] CharacterData: CharacterDataType = jsNative
    let [<Global>] ClientRect: ClientRectType = jsNative
    // let [<Global>] ClientRectList: ClientRectListType = jsNative
    // let [<Global>] ClipboardEvent: ClipboardEventType = jsNative
    // let [<Global>] CloseEvent: CloseEventType = jsNative
    // let [<Global>] CommandEvent: CommandEventType = jsNative
    // let [<Global>] Comment: CommentType = jsNative
    // let [<Global>] CompositionEvent: CompositionEventType = jsNative
    // let [<Global>] Console: ConsoleType = jsNative
    // let [<Global>] ConvolverNode: ConvolverNodeType = jsNative
    // let [<Global>] Coordinates: CoordinatesType = jsNative
    // let [<Global>] Crypto: CryptoType = jsNative
    // let [<Global>] CryptoKey: CryptoKeyType = jsNative
    // let [<Global>] CryptoKeyPair: CryptoKeyPairType = jsNative
    // let [<Global>] CustomEvent: CustomEventType = jsNative
    let [<Global>] DOMException: DOMExceptionType = jsNative
    let [<Global>] DOMImplementation: DOMImplementationType = jsNative
    // let [<Global>] DOMParser: DOMParserType = jsNative
    let [<Global>] DOMStringList: DOMStringListType = jsNative
    let [<Global>] DOMStringMap: DOMStringMapType = jsNative
    let [<Global>] DOMTokenList: DOMTokenListType = jsNative
    // let [<Global>] DataCue: DataCueType = jsNative
    // let [<Global>] DataTransfer: DataTransferType = jsNative
    // let [<Global>] DataTransferItem: DataTransferItemType = jsNative
    // let [<Global>] DataTransferItemList: DataTransferItemListType = jsNative
    // let [<Global>] DeferredPermissionRequest: DeferredPermissionRequestType = jsNative
    // let [<Global>] DelayNode: DelayNodeType = jsNative
    // let [<Global>] DeviceAcceleration: DeviceAccelerationType = jsNative
    // let [<Global>] DeviceMotionEvent: DeviceMotionEventType = jsNative
    // let [<Global>] DeviceOrientationEvent: DeviceOrientationEventType = jsNative
    // let [<Global>] DeviceRotationRate: DeviceRotationRateType = jsNative
    let [<Global>] Document: DocumentType = jsNative
    let [<Global>] DocumentFragment: DocumentFragmentType = jsNative
    let [<Global>] DocumentType: DocumentTypeType = jsNative
    // let [<Global>] DragEvent: DragEventType = jsNative
    // let [<Global>] DynamicsCompressorNode: DynamicsCompressorNodeType = jsNative
    let [<Global>] Element: ElementType = jsNative
    // let [<Global>] ErrorEvent: ErrorEventType = jsNative
    // let [<Global>] Event: EventType = jsNative
    // let [<Global>] EventTarget: EventTargetType = jsNative
    // let [<Global>] External: ExternalType = jsNative
    // let [<Global>] File: FileType = jsNative
    // let [<Global>] FileList: FileListType = jsNative
    // let [<Global>] FileReader: FileReaderType = jsNative
    // let [<Global>] FocusEvent: FocusEventType = jsNative
    // let [<Global>] FormData: FormDataType = jsNative
    // let [<Global>] GainNode: GainNodeType = jsNative
    // let [<Global>] Gamepad: GamepadType = jsNative
    // let [<Global>] GamepadButton: GamepadButtonType = jsNative
    // let [<Global>] GamepadEvent: GamepadEventType = jsNative
    // let [<Global>] Geolocation: GeolocationType = jsNative
    let [<Global>] HTMLAllCollection: HTMLAllCollectionType = jsNative
    let [<Global>] HTMLAnchorElement: HTMLAnchorElementType = jsNative
    let [<Global>] HTMLAreaElement: HTMLAreaElementType = jsNative
    let [<Global>] HTMLAreasCollection: HTMLAreasCollectionType = jsNative
    let [<Global>] HTMLAudioElement: HTMLAudioElementType = jsNative
    let [<Global>] HTMLBRElement: HTMLBRElementType = jsNative
    let [<Global>] HTMLBaseElement: HTMLBaseElementType = jsNative
    let [<Global>] HTMLBlockElement: HTMLBlockElementType = jsNative
    let [<Global>] HTMLBodyElement: HTMLBodyElementType = jsNative
    let [<Global>] HTMLButtonElement: HTMLButtonElementType = jsNative
    let [<Global>] HTMLCanvasElement: HTMLCanvasElementType = jsNative
    let [<Global>] HTMLCollection: HTMLCollectionType = jsNative
    let [<Global>] HTMLDDElement: HTMLDDElementType = jsNative
    let [<Global>] HTMLDListElement: HTMLDListElementType = jsNative
    let [<Global>] HTMLDTElement: HTMLDTElementType = jsNative
    let [<Global>] HTMLDataListElement: HTMLDataListElementType = jsNative
    let [<Global>] HTMLDirectoryElement: HTMLDirectoryElementType = jsNative
    let [<Global>] HTMLDivElement: HTMLDivElementType = jsNative
    let [<Global>] HTMLDocument: HTMLDocumentType = jsNative
    let [<Global>] HTMLElement: HTMLElementType = jsNative
    let [<Global>] HTMLEmbedElement: HTMLEmbedElementType = jsNative
    let [<Global>] HTMLFieldSetElement: HTMLFieldSetElementType = jsNative
    let [<Global>] HTMLFontElement: HTMLFontElementType = jsNative
    let [<Global>] HTMLFormElement: HTMLFormElementType = jsNative
    let [<Global>] HTMLFrameElement: HTMLFrameElementType = jsNative
    let [<Global>] HTMLFrameSetElement: HTMLFrameSetElementType = jsNative
    let [<Global>] HTMLHRElement: HTMLHRElementType = jsNative
    let [<Global>] HTMLHeadElement: HTMLHeadElementType = jsNative
    let [<Global>] HTMLHeadingElement: HTMLHeadingElementType = jsNative
    let [<Global>] HTMLHtmlElement: HTMLHtmlElementType = jsNative
    let [<Global>] HTMLIFrameElement: HTMLIFrameElementType = jsNative
    let [<Global>] HTMLImageElement: HTMLImageElementType = jsNative
    let [<Global>] HTMLInputElement: HTMLInputElementType = jsNative
    let [<Global>] HTMLLIElement: HTMLLIElementType = jsNative
    let [<Global>] HTMLLabelElement: HTMLLabelElementType = jsNative
    let [<Global>] HTMLLegendElement: HTMLLegendElementType = jsNative
    let [<Global>] HTMLLinkElement: HTMLLinkElementType = jsNative
    let [<Global>] HTMLMapElement: HTMLMapElementType = jsNative
    let [<Global>] HTMLMediaElement: HTMLMediaElementType = jsNative
    let [<Global>] HTMLMenuElement: HTMLMenuElementType = jsNative
    let [<Global>] HTMLMetaElement: HTMLMetaElementType = jsNative
    let [<Global>] HTMLModElement: HTMLModElementType = jsNative
    let [<Global>] HTMLNextIdElement: HTMLNextIdElementType = jsNative
    let [<Global>] HTMLOListElement: HTMLOListElementType = jsNative
    let [<Global>] HTMLObjectElement: HTMLObjectElementType = jsNative
    let [<Global>] HTMLOptGroupElement: HTMLOptGroupElementType = jsNative
    let [<Global>] HTMLOptionElement: HTMLOptionElementType = jsNative
    let [<Global>] HTMLParagraphElement: HTMLParagraphElementType = jsNative
    let [<Global>] HTMLParamElement: HTMLParamElementType = jsNative
    let [<Global>] HTMLPhraseElement: HTMLPhraseElementType = jsNative
    let [<Global>] HTMLPreElement: HTMLPreElementType = jsNative
    let [<Global>] HTMLProgressElement: HTMLProgressElementType = jsNative
    let [<Global>] HTMLQuoteElement: HTMLQuoteElementType = jsNative
    let [<Global>] HTMLScriptElement: HTMLScriptElementType = jsNative
    let [<Global>] HTMLSelectElement: HTMLSelectElementType = jsNative
    let [<Global>] HTMLSourceElement: HTMLSourceElementType = jsNative
    let [<Global>] HTMLSpanElement: HTMLSpanElementType = jsNative
    let [<Global>] HTMLStyleElement: HTMLStyleElementType = jsNative
    let [<Global>] HTMLTableCaptionElement: HTMLTableCaptionElementType = jsNative
    let [<Global>] HTMLTableCellElement: HTMLTableCellElementType = jsNative
    let [<Global>] HTMLTableColElement: HTMLTableColElementType = jsNative
    let [<Global>] HTMLTableDataCellElement: HTMLTableDataCellElementType = jsNative
    let [<Global>] HTMLTableElement: HTMLTableElementType = jsNative
    let [<Global>] HTMLTableHeaderCellElement: HTMLTableHeaderCellElementType = jsNative
    let [<Global>] HTMLTableRowElement: HTMLTableRowElementType = jsNative
    let [<Global>] HTMLTableSectionElement: HTMLTableSectionElementType = jsNative
    let [<Global>] HTMLTextAreaElement: HTMLTextAreaElementType = jsNative
    let [<Global>] HTMLTitleElement: HTMLTitleElementType = jsNative
    let [<Global>] HTMLTrackElement: HTMLTrackElementType = jsNative
    let [<Global>] HTMLUListElement: HTMLUListElementType = jsNative
    let [<Global>] HTMLUnknownElement: HTMLUnknownElementType = jsNative
    let [<Global>] HTMLVideoElement: HTMLVideoElementType = jsNative
    // let [<Global>] HashChangeEvent: HashChangeEventType = jsNative
    // let [<Global>] History: HistoryType = jsNative
    // let [<Global>] IIRFilterNode: IIRFilterNodeType = jsNative
    let [<Global>] ImageData: ImageDataType = jsNative
    // let [<Global>] KeyboardEvent: KeyboardEventType = jsNative
    // let [<Global>] Location: LocationType = jsNative
    // let [<Global>] LongRunningScriptDetectedEvent: LongRunningScriptDetectedEventType = jsNative
    // let [<Global>] MediaElementAudioSourceNode: MediaElementAudioSourceNodeType = jsNative
    // let [<Global>] MediaError: MediaErrorType = jsNative
    // let [<Global>] MediaList: MediaListType = jsNative
    // let [<Global>] MediaQueryList: MediaQueryListType = jsNative
    // let [<Global>] MediaSource: MediaSourceType = jsNative
    // let [<Global>] MediaStream: MediaStreamType = jsNative
    // let [<Global>] MediaStreamAudioDestinationNode: MediaStreamAudioDestinationNodeType = jsNative
    // let [<Global>] MediaStreamAudioSourceNode: MediaStreamAudioSourceNodeType = jsNative
    // let [<Global>] MessageChannel: MessageChannelType = jsNative
    // let [<Global>] MessageEvent: MessageEventType = jsNative
    // let [<Global>] MessagePort: MessagePortType = jsNative
    // let [<Global>] MimeType: MimeTypeType = jsNative
    // let [<Global>] MimeTypeArray: MimeTypeArrayType = jsNative
    // let [<Global>] MouseEvent: MouseEventType = jsNative
    // let [<Global>] MouseWheelEvent: MouseWheelEventType = jsNative
    let [<Global>] NamedNodeMap: NamedNodeMapType = jsNative
    // let [<Global>] NavigationCompletedEvent: NavigationCompletedEventType = jsNative
    // let [<Global>] NavigationEvent: NavigationEventType = jsNative
    // let [<Global>] NavigationEventWithReferrer: NavigationEventWithReferrerType = jsNative
    // let [<Global>] Navigator: NavigatorType = jsNative
    let [<Global>] Node: NodeType = jsNative
    let [<Global>] NodeFilter: NodeFilterType = jsNative
    let [<Global>] NodeIterator: NodeIteratorType = jsNative
    let [<Global>] NodeList: NodeListType = jsNative
    // let [<Global>] OES_element_index_uint: OES_element_index_uintType = jsNative
    // let [<Global>] OES_standard_derivatives: OES_standard_derivativesType = jsNative
    // let [<Global>] OES_texture_float: OES_texture_floatType = jsNative
    // let [<Global>] OES_texture_float_linear: OES_texture_float_linearType = jsNative
    // let [<Global>] OfflineAudioCompletionEvent: OfflineAudioCompletionEventType = jsNative
    // let [<Global>] OfflineAudioContext: OfflineAudioContextType = jsNative
    // let [<Global>] OscillatorNode: OscillatorNodeType = jsNative
    // let [<Global>] PageTransitionEvent: PageTransitionEventType = jsNative
    // let [<Global>] PannerNode: PannerNodeType = jsNative
    // let [<Global>] PerfWidgetExternal: PerfWidgetExternalType = jsNative
    // let [<Global>] Performance: PerformanceType = jsNative
    // let [<Global>] PerformanceEntry: PerformanceEntryType = jsNative
    // let [<Global>] PerformanceMark: PerformanceMarkType = jsNative
    // let [<Global>] PerformanceMeasure: PerformanceMeasureType = jsNative
    // let [<Global>] PerformanceNavigation: PerformanceNavigationType = jsNative
    // let [<Global>] PerformanceNavigationTiming: PerformanceNavigationTimingType = jsNative
    // let [<Global>] PerformanceResourceTiming: PerformanceResourceTimingType = jsNative
    // let [<Global>] PerformanceTiming: PerformanceTimingType = jsNative
    // let [<Global>] PeriodicWave: PeriodicWaveType = jsNative
    // let [<Global>] PermissionRequest: PermissionRequestType = jsNative
    // let [<Global>] PermissionRequestedEvent: PermissionRequestedEventType = jsNative
    // let [<Global>] Plugin: PluginType = jsNative
    // let [<Global>] PluginArray: PluginArrayType = jsNative
    // let [<Global>] PointerEvent: PointerEventType = jsNative
    // let [<Global>] PopStateEvent: PopStateEventType = jsNative
    // let [<Global>] Position: PositionType = jsNative
    // let [<Global>] PositionError: PositionErrorType = jsNative
    // let [<Global>] ProcessingInstruction: ProcessingInstructionType = jsNative
    // let [<Global>] ProgressEvent: ProgressEventType = jsNative
    let [<Global>] Range: RangeType = jsNative
    // let [<Global>] Screen: ScreenType = jsNative
    // let [<Global>] ScriptNotifyEvent: ScriptNotifyEventType = jsNative
    // let [<Global>] ScriptProcessorNode: ScriptProcessorNodeType = jsNative
    let [<Global>] Selection: SelectionType = jsNative
    let [<Global>] SourceBuffer: SourceBufferType = jsNative
    let [<Global>] SourceBufferList: SourceBufferListType = jsNative
    // let [<Global>] SpatialListener: SpatialListenerType = jsNative
    // let [<Global>] SpatialPannerNode: SpatialPannerNodeType = jsNative
    // let [<Global>] StereoPannerNode: StereoPannerNodeType = jsNative
    // let [<Global>] Storage: StorageType = jsNative
    // let [<Global>] StorageEvent: StorageEventType = jsNative
    // let [<Global>] StyleMedia: StyleMediaType = jsNative
    // let [<Global>] StyleSheet: StyleSheetType = jsNative
    // let [<Global>] StyleSheetList: StyleSheetListType = jsNative
    // let [<Global>] StyleSheetPageList: StyleSheetPageListType = jsNative
    // let [<Global>] SubtleCrypto: SubtleCryptoType = jsNative
    // let [<Global>] Text: TextType = jsNative
    // let [<Global>] TextEvent: TextEventType = jsNative
    // let [<Global>] TextMetrics: TextMetricsType = jsNative
    // let [<Global>] TextRange: TextRangeType = jsNative
    // let [<Global>] TextRangeCollection: TextRangeCollectionType = jsNative
    // let [<Global>] TextTrack: TextTrackType = jsNative
    // let [<Global>] TextTrackCue: TextTrackCueType = jsNative
    // let [<Global>] TextTrackCueList: TextTrackCueListType = jsNative
    // let [<Global>] TextTrackList: TextTrackListType = jsNative
    // let [<Global>] TimeRanges: TimeRangesType = jsNative
    // let [<Global>] Touch: TouchType = jsNative
    // let [<Global>] TouchEvent: TouchEventType = jsNative
    // let [<Global>] TouchList: TouchListType = jsNative
    // let [<Global>] TrackEvent: TrackEventType = jsNative
    // let [<Global>] TransitionEvent: TransitionEventType = jsNative
    // let [<Global>] TreeWalker: TreeWalkerType = jsNative
    // let [<Global>] UIEvent: UIEventType = jsNative
    // let [<Global>] UnviewableContentIdentifiedEvent: UnviewableContentIdentifiedEventType = jsNative
    // let [<Global>] ValidityState: ValidityStateType = jsNative
    // let [<Global>] VideoPlaybackQuality: VideoPlaybackQualityType = jsNative
    // let [<Global>] VideoTrack: VideoTrackType = jsNative
    // let [<Global>] VideoTrackList: VideoTrackListType = jsNative
    // let [<Global>] WebSocket: WebSocketType = jsNative
    // let [<Global>] WheelEvent: WheelEventType = jsNative
    // let [<Global>] Window: WindowType = jsNative
    let [<Global>] Worker: WorkerType = jsNative
    let [<Global>] XMLDocument: XMLDocumentType = jsNative
    // let [<Global>] HTMLTemplateElement: HTMLTemplateElementType = jsNative
    // let [<Global>] HTMLPictureElement: HTMLPictureElementType = jsNative
    // let [<Global>] Audio: AudioType = jsNative
    // let [<Global>] Image: ImageType = jsNative
    let [<Global>] animationStartTime: float = jsNative
    // let [<Global>] clientInformation: Navigator = jsNative
    let [<Global>] closed: bool = jsNative
    // let [<Global>] crypto: Crypto = jsNative
    let [<Global>] defaultStatus: string = jsNative
    let [<Global>] devicePixelRatio: float = jsNative
    let [<Global>] doNotTrack: string = jsNative
    let [<Global>] document: Document = jsNative
    // let [<Global>] ``event``: Event = jsNative
    // let [<Global>] ``external``: External = jsNative
    let [<Global>] frameElement: Element = jsNative
    let [<Global>] frames: Window = jsNative
    let [<Global>] history: History = jsNative
    let [<Global>] innerHeight: float = jsNative
    let [<Global>] innerWidth: float = jsNative
    let [<Global>] length: int = jsNative
    let [<Global>] location: Location = jsNative
    let [<Global>] locationbar: BarProp = jsNative
    let [<Global>] menubar: BarProp = jsNative
    let [<Global>] name: string = jsNative
    // let [<Global>] navigator: Navigator = jsNative
    let [<Global>] offscreenBuffering: bool = jsNative
    let [<Global>] opener: Window = jsNative
    let [<Global>] orientation: string = jsNative
    let [<Global>] outerHeight: float = jsNative
    let [<Global>] outerWidth: float = jsNative
    let [<Global>] pageXOffset: float = jsNative
    let [<Global>] pageYOffset: float = jsNative
    let [<Global>] parent: Window = jsNative
    let [<Global>] performance: Performance = jsNative
    let [<Global>] personalbar: BarProp = jsNative
    let [<Global>] screen: Screen = jsNative
    let [<Global>] screenLeft: float = jsNative
    let [<Global>] screenTop: float = jsNative
    let [<Global>] screenX: float = jsNative
    let [<Global>] screenY: float = jsNative
    let [<Global>] scrollX: float = jsNative
    let [<Global>] scrollY: float = jsNative
    let [<Global>] scrollbars: BarProp = jsNative
    let [<Global>] self: Window = jsNative
    let [<Global>] status: string = jsNative
    let [<Global>] statusbar: BarProp = jsNative
    // let [<Global>] styleMedia: StyleMedia = jsNative
    let [<Global>] toolbar: BarProp = jsNative
    let [<Global>] top: Window = jsNative
    let [<Global>] window: Window = jsNative
    let [<Global>] URL: URLType = jsNative
    let [<Global>] URLSearchParams: URLSearchParamsType = jsNative
    let [<Global>] sessionStorage: Storage = jsNative
    let [<Global>] localStorage: Storage = jsNative
    let [<Global>] console: Console = jsNative

namespace Fable.Import

[<System.Obsolete("Use Fable.Browser.Dom")>]
module Browser =
    /// Use Fable.Browser.Dom
    let obsolete<'T> : 'T = failwith "Use Fable.Browser.Dom"